# Generated by Django 4.0.4 on 2022-04-19 16:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 18, 51, 33, 751538)),
        ),
        migrations.AddField(
            model_name='sortie',
            name='difficulte',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
