# Generated by Django 4.0.4 on 2022-04-19 16:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0004_sortie_date_sortie_sortie_difficulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 18, 54, 16, 561682)),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='difficulte',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='nbParticipants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
