# Generated by Django 4.0.4 on 2022-04-19 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0005_alter_sortie_date_sortie_alter_sortie_difficulte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraire',
            old_name='difficulty',
            new_name='difficulte',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='duration',
            new_name='duree',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='itineraire',
            name='altitudeDepart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='altitudeMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='deniveleNegatif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='denivelePositif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='pointDeDepart',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
