# Generated by Django 4.0.4 on 2022-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0006_rename_difficulty_itineraire_difficulte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
