# Generated by Django 4.0.4 on 2022-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0007_itineraire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_Y_Itineraire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_Y_pointDeDepart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_x_Itineraire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_x_pointDeDepart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitudeDepart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitudeMax',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='deniveleNegatif',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivelePositif',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
