# Generated by Django 4.0.4 on 2022-04-25 15:00

from django.db import migrations, models
import django.db.models.deletion
import itineraires.models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0008_alter_itineraire_altitudedepart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=itineraires.models.itineraire_img_name)),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.sortie')),
            ],
        ),
    ]
