# Generated by Django 4.0.4 on 2022-04-25 19:48

from django.db import migrations, models
import itineraires.models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0010_rename_img_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=itineraires.models.itineraire_img_name),
        ),
    ]
