# Generated by Django 4.0.4 on 2022-05-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0012_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='sortie',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='itineraire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire'),
            preserve_default=False,
        ),
    ]
