# Generated by Django 4.0.4 on 2022-05-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0013_remove_commentaire_sortie_commentaire_itineraire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='commentaire',
            new_name='text',
        ),
    ]
