# Generated by Django 4.0.4 on 2022-05-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0014_rename_commentaire_commentaire_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='text',
            new_name='texte',
        ),
    ]
