# Generated by Django 4.0.4 on 2022-05-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0010_alter_itineraire_coordonne_y_itineraire_and_more'),
        ('itineraires', '0015_rename_text_commentaire_texte'),
    ]

    operations = [
    ]
