# Generated by Django 4.0.4 on 2022-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0016_merge_20220504_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='Coordonne_Y_Itineraire',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='Coordonne_Y_pointDeDepart',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='Coordonne_x_Itineraire',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='Coordonne_x_pointDeDepart',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16, null=True),
        ),
    ]
