# Generated by Django 4.0.4 on 2022-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0019_rename_coordonne_y_itineraire_itineraire_latitude_itineraire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='latitude_Itineraire',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='latitude_pointDeDepart',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='longitude_Itineraire',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='longitude_pointDeDepart',
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_Y_Itineraire',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_Y_pointDeDepart',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_x_Itineraire',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='Coordonne_x_pointDeDepart',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10, null=True),
        ),
    ]
