# Generated by Django 4.0.4 on 2022-05-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0020_remove_itineraire_latitude_itineraire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraire',
            old_name='Coordonne_Y_Itineraire',
            new_name='latitude_Itineraire',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='Coordonne_Y_pointDeDepart',
            new_name='latitude_pointDeDepart',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='Coordonne_x_Itineraire',
            new_name='longitude_Itineraire',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='Coordonne_x_pointDeDepart',
            new_name='longitude_pointDeDepart',
        ),
    ]
