# Generated by Django 4.0.4 on 2022-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0021_rename_coordonne_y_itineraire_itineraire_latitude_itineraire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_Itineraire',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='latitude_pointDeDepart',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_Itineraire',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='longitude_pointDeDepart',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20, null=True),
        ),
    ]
